Callbacks
wolvampire/wolpAIre pull request #2
Opened 2019-02-23 13:41 UTC by selimbat

Ajout des callbacks et de l'initialisation des tiles

2019-02-23 13:42 UTC, selimbat commented
@paternose est ce que tu peux compléter la callback BYE ?

2019-02-23 13:47 UTC, matetb commented on board_tile.py
> +        self.type="EMPT"  # among "WERE", "VAMP", "HUM" (for humans), "EMPT"
on devrait changer le nom de l'attribut "type" en "faction" pour éviter les conflits de nommage un peu crades

2019-02-23 13:47 UTC, matetb commented on board_tile.py
>  class BoardTile():
mettre en camel_case ?

2019-02-23 13:47 UTC, matetb commented on board_tile.py
> +    def __init__(self, x, y):
rajouter en argument optionnel le nb et la faction

2019-02-23 13:48 UTC, matetb commented on game_client.py
> +        self.__board = [[0]*m]*n
au lieu de 0, plutôt mettre une case board_tile vide ?

2019-02-23 13:49 UTC, matetb commented on game_client.py
> +                self.__board[x][y] = board_tile(x,y,faction="HUM")
le serveur devrait envoyer le nombre d'humains dans ces cases là, quand est-ce qu'il nous les envoie ?

2019-02-23 13:50 UTC, matetb commented on game_client.py
> +    def callback_upd(self, nChanges, changesInfosList):
quand on reçoit cette trame ça veut dire qu'il faut qu'on réponde une décision

2019-02-23 13:52 UTC, matetb requested changes
8/10

2019-02-25 13:10 UTC, clounarae commented on board_tile.py
> +        self.type="EMPT"  # among "WERE", "VAMP", "HUM" (for humans), "EMPT"
Quid de créer des constantes WERE="werevoves",VAMP=vampires", etc c'est plus joli et moins cause d'erreurs que de coller des str partout

2019-02-25 13:17 UTC, JihaneBennis commented on game_client.py
> +                if (nHum*nVamp == 0) and (nHum*nWere == 0) and (nVamp*nWere == 0):
Ajouter un commentaire pour expliquer la condition :)

2019-02-25 13:17 UTC, JihaneBennis commented on game_client.py
> +                             if board_tile.type == self.__us]
type ou faction ?

2019-02-25 13:17 UTC, clounarae approved these changes

2019-02-25 14:42 UTC, merged